version: 1.0.{build}
# docker support
image: Ubuntu2004

skip_tags: true
max_jobs: 100
build: none
clone_folder: "$HOME/sos"
clone_depth: 50
shallow_clone: false

services:
  - docker

environment:
  matrix:
    - PYTHON: "venv3.8"
    - PYTHON: "venv3.9"

install:
  - export PATH=/home/appveyor/$PYTHON/bin:$PATH
  - echo $PATH
  - echo $PYTHON
  # packages required by SoS
  - pip install -r requirements_dev.txt
  - pip install .

test_script:
  - cd test
  - sh build_test_docker.sh
  - python run_tests.py

  #
  #on_finish:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# do not report coverage because codacy only accept coverage for each commit
#
#on_success:
#    - coverage xml
#    - python-codacy-coverage -r coverage.xml

notifications:
  - provider: Email
    to:
      - ben.bob@gmail.com
    on_build_status_changed: true
