version: 1.0.{build}
# docker support
image: Visual Studio 2022

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#branches:
#    only:
#        - master

skip_tags: true

max_jobs: 100

build: none

clone_folder: c:\projects\sos
clone_depth: 50
shallow_clone: false

environment:
  matrix:
    - PYTHON: "C:\Python39"

install:
  - set PYTHON="C:\Python39"
  - set PATH=%PYTHON%;%PATH%
  # packages required by SoS
  - pip install jedi pyyaml psutil tqdm
  - pip install fasteners pygments ipython ptpython networkx pydot pydotplus nose
  - pip install entrypoints numpy pandas

  # install sos
  - pip install pytest
  - pip install .

test_script:
  - cd test
  - pytest -v
    #
    #on_finish:
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# do not report coverage because codacy only accept coverage for each commit
#
#on_success:
#    - coverage xml
#    - python-codacy-coverage -r coverage.xml

notifications:
  - provider: Email
    to:
      - ben.bob@gmail.com
    on_build_status_changed: true
