version: 1.0.{build}

# docker support
#image: Visual Studio 2017

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


branches:
    only:
        - master

skip_tags: true

max_jobs: 100

build: none

clone_folder: c:\projects\sos
clone_depth: 50
shallow_clone: false

environment:
    matrix:
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_VERSION: 3.6

        - PYTHON: "C:\\Miniconda35-x64"
          PYTHON_VERSION: 3.5

install:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # 
    # add docker
    - pip install docker
    # packages required by SoS
    - pip install spyder jedi notebook nbconvert nbformat pyyaml psutil tqdm 
    - pip install fasteners pygments ipython ptpython networkx pydotplus nose 
    # https://github.com/jupyter/jupyter/issues/150
    - pip install entrypoints
    - pip install jupyter
    # install r kernel
    - conda install -c r r-essentials r-feather
    - conda install -c conda-forge feather-format
    # install bash kernel
    #- pip install bash_kernel
    #- python -m bash_kernel.install

    # install sos
    - python setup.py install
      
test_script:
    - cd test
    - python run_tests ..\sos\jupyter\test ..\sos\Python3\test ..\sos\R\test ..\test
    #- python run_tests ..\sos\docker\test
    #- python run_tests ..\sos\Bash\test
    # - ./run_tests ../sos/JavaScript/test 
    #- ./run_tests ../sos/rq/test

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


notifications:
    - provider: Email
      to:
        - ben.bob@gmail.com
      on_build_status_changed: true


