dist: trusty
group: edge
os:
    - linux
    # travis does not support python on osx yet (https://github.com/travis-ci/travis-ci/issues/4729)
language: python
python:
    - "3.6"

addons:
  apt:
    update: true
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
      - git
      - build-essential
      - libtool
      - autotools-dev
      - automake
      - autoconf
      - uuid-dev
      - libmagickwand-dev
      - libmagickcore5-extra
      - graphviz
      - octave
      - ruby-full

before_install:
    # install anaconda Python 3
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget  https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # downgrade python if needed
    - conda create -n python_test python=$TRAVIS_PYTHON_VERSION anaconda
    - source activate python_test

    # R
    - conda install -c r r-markdown r-rmarkdown r-base64enc  pandoc
    # add docker
    - pip install docker
    # packages required by SoS
    - pip install pyyaml psutil tqdm
    - pip install fasteners pygments networkx pydot pydotplus graphviz imageio pillow
    # https://github.com/jupyter/jupyter/issues/150
    - pip install entrypoints jupyter coverage codacy-coverage pytest pytest-cov python-coveralls
    - conda install pandas numpy gxx_linux-64

    # singularity
    - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers
    - pip install sregistry[all]
    - cd /tmp && wget https://github.com/singularityware/singularity/archive/2.6.0.tar.gz && tar zxf 2.6.0.tar.gz
    - cd /tmp/singularity-2.6.0 && ./autogen.sh && ./configure --prefix=/usr/local || cat config.log
    - cd /tmp/singularity-2.6.0 && make && sudo make install

sudo: required
services:
    - docker
install: "pip install ."
before_script:
    - cd test
    - sh build_test_docker.sh
script:
    - pytest -x -v --cov sos --cov-config ../.coveragerc --cov-report=xml;

after_success:
    - coverage combine;
    - coveralls

notifications:
    email:
        recipients:
            - ben.bob@gmail.com
        on_success: never
        on_failure: always

