version: 1.0.{build}
branches:
    only:
        - master

skip_tags: true

max_jobs: 100

build: none

clone_folder: c:\projects\sos
clone_depth: 50
shallow_clone: false

matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 64
      VCVARSALL: x64

install:
    - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
    - cmd: python setup.py install

test_script:
    - ./run_tests ../test
    - ./run_tests ../sos/docker/test
    - ./run_tests ../sos/Bash/test
    - ./run_tests ../sos/Python2/test
    - ./run_tests ../sos/Python3/test
    - ./run_tests ../sos/R/test
    - ./run_tests ../sos/jupyter/test 
    # - ./run_tests ../sos/JavaScript/test 
    #- ./run_tests ../sos/rq/test
notifications:
    - provider: Email
      to:
        - ben.bob@gmail.com
      on_build_status_changed: true
